config/routes.rb
Rails.application.routes.draw do

  resource :search, only: [:show]
  resources :stores, :except => [:index] do
    post 'follow', :to => 'followings#create'
    delete 'unfollow', :to => 'followings#destroy'
    collection do
      get 'dashboard'
    end
  end

  resources :products do
    resources :reviews, except: [:index, :show]

    collection do
      get 'search'
    end
  end

  get 'index', :to => 'pages#index'

  get 'sell', :to => 'pages#sell'

  get 'about', :to => 'pages#about'

  get 'contact', :to => 'pages#contact'

  get 'blog', :to => 'pages#blog'

  get 'support', :to => 'pages#support'

  get 'terms', :to => 'pages#terms'

  get 'privacy', :to => 'pages#privacy'

  get 'advertise', :to => 'pages#advertise'

  resources :categories, :only => [:index, :show]
  resources :subcategories, :only => [:index, :show]


  # get 'stores/dashboard'
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}

  # devise_scope :user do
  #   get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  resources :users, :only => [:show]
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products, through: :subcategories
  has_many :subcategories
  has_many :stores

end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :store
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :reciepient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true

  scope :unread, ->{ where(read_at: nil) }
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :images, ImageUploader

  belongs_to :store
  has_many :reviews
  belongs_to :category
  belongs_to :subcategory
  validates :name, :price, :description, :category, :images, :stock, presence: true
  validates :slug, uniqueness: true, presence: true

  before_validation :generate_slug

  def to_param
    "#{id}-#{name}".parameterize
  end

  def generate_slug
    self.slug ||= name.parameterize
  end
end

app/models/review.rb
class Review < ApplicationRecord

    belongs_to :product
    belongs_to :user

    validates :comment, :rating, presence: true
    
end

app/models/search.rb
class Search
	attr_reader :term

	def to_partial_path
		'searches/show'
	end

	def initialize(options = {})
		@term = options.fetch(:term, "")
	end

	def found_products
		products
	end

	def found_stores
		stores
	end

	private

	def stores
		@store = Store.where("name iLike ? or description iLike ?", search_term, search_term)
	end

	def products
    @products = Product.where("name iLIKE ? or description iLIKE ?", search_term, search_term)
	end

	def search_term
		"%#{term}%"
	end
	
end

app/models/store.rb
class Store < ApplicationRecord
  is_impressionable
  RESTRICTED_NAMES = %w[www]

  mount_uploader :logo, ImageUploader

  belongs_to :user
  belongs_to :category
  
  
  has_many :followings
  has_many :followers, through: :followings


  has_many :products, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :name, presence: true,
                  uniqueness: { case_sensitive: false},
                  format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters'},
                  exclusion: { in: RESTRICTED_NAMES, message: 'restricted'}

  validates :description, :category, presence: true
  validates :slug, uniqueness: true, presence: true

  before_validation :generate_slug

  
  # Get all stores tagged with name

  def self.tagged_with(name)
    Tag.find_by!(name: name).stores
  end

  # tags and taggings setting tags
    def all_tags=(names)
      self.tags = names.split(',').map do |name|
        Tag.where(name: name).first_or_create!
      end
    end

  # Getting tags
    def all_tags
      tags.map(&:name).join(", ")
    end

  # COnverts id and name to string for pretty urls
    def to_param
      "#{id}-#{name}".parameterize
    end

  # Generates slug for future use
    def generate_slug
      self.slug ||= name.parameterize
    end


end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  
  belongs_to :category
  has_many :products

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :stores, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord

  belongs_to :store
  belongs_to :tag
  
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :confirmable, :omniauthable, :omniauth_providers => [:facebook]

  mount_uploader :avatar, ImageUploader

  has_one :store, dependent: :destroy
  has_many :reviews
  has_many :notifications, foreign_key: :reciepient_id
  
  # accepts_nested_attributes_for :store

  def following? store, user
    store.follower_ids.include? user.id
  end

  def follow (store, user)
    store.followers << user
  end

  def unfollow (store, user)
    store.followers.delete(user.id)
  end

  

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|

      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name # assuming the user model has a name
      user.remote_avatar_url = auth.info.image

      # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      #  user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/form_helper.rb
module FormHelper

  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: "help-block")
  end


  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors} " do
      concat form.label(field, class: "control-label") if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end

end

app/helpers/layout_helper.rb
module LayoutHelper

  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash-#{name}")
      end
    end
  end

  def show_layout_flash
    @layout_flash.nil? ? true : @layout_flash
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/steppy_helper.rb
module SteppyHelper
end

app/helpers/store_helper.rb
module StoreHelper
	def follow_button store

		if  current_user && current_user != store.user 
			if current_user.following?(store, current_user)
				button_to 'Unfollow', store_unfollow_path(store), method: :delete, class: "btn btn-danger button"
			else
				button_to 'Follow', store_follow_path(store), class: "btn btn-danger button"
			end
		end
		
	end
end

app/views/pages/_carousel.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3 class="text-center">Browse Categories</h3>
            <ul>
              <% @categories.each do |c| %>
                <li><%= c.name %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-sm-9">
        <div class=" panel panel-default">
          <div class="panel-heading">Latest</div>
          <div class="panel-body">
            <% @latest_products.each do |p|%>
              <div class="media">
                <div class="media-left">
                    <%= image_tag(p.image.thumb)%>
                </div>
                <div class="media-body">
                    <h4 class="media-heading"><%= p.name %></h4>
                    <p><%= p.description %></p>
                    <p><%= p.price %></p> <span>By: <%= p.store.name %> </span>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/about.html.erb
<div class="container">
  <div class="section pt6">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="text-center">
          <h1 class="amount">Get to know Claeus</h1>
          <h4>Our mission is to offer small businesses and emerging brands an ecosystem to start selling online while building their brands.</h4>
          <p class="lead">We are much more than just a marketplace, we are about discovering and connecting amazing brands to customers.</p>

          <hr>

          <p class="lead">In April, 2016 <strong>Nana Adjei Manu(Joe Claeus)</strong> started claeus.com.
            His main aim was to offer sellers a unique online ecosystem to offer their products for sale while
            engaging and retaining their customers.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <div class="section pt6">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">

        <div class="text-center amount">
          <h1>Get in touch</h1>

            <h2 class="lead amount">claeus@gmail.com</h2>

            <h2 class="lead amount">+233200864593</h2>
        </div>


        <!-- <form class="" action="index.html" method="post">
          <div class="form-group">
            <label for="email">Your Email</label>
            <input type="text" class="form-control input-lg" id="email" placeholder="">
            <p class="help-block">Your email goes here.</p>
          </div>
          <div class="form-group ">
            <label for="name">Your Name</label>
            <input type="text" class="form-control input-lg" id="name" placeholder="">
            <p class="help-block">Add your name.</p>
          </div>
          <div class="form-group">
            <label for="message">Your Message</label>
            <textarea type="text" class="form-control input-lg" cols="30" rows="10" id="message" placeholder=""></textarea>
            <p class="help-block">Your message/inquiry goes here.</p>
          </div>
          <p class="text-right"><button type="button" name="button" class="btn btn-danger btn-lg">Send</button></p>
        </form> -->
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<section>
    <div class="home-hero">
      <div class="container-fluid">
        <h1>Looking for something?</h1>
        <p class="lead">From electronics to home decor, <strong>There's a store!!!</strong></p>
      </div>
    </div>
</section>

<section class="page-section">
  <div class="container">
    <h2 class="text-center">Shop by category</h2> 
    <div class="row">
      <% @categories.each do |c| %>
        <div class="col-md-3 col-sm-6 col-xs-12 col-lg-3">
          <div class="card">
            <%= link_to c.name, c %>
          </div>
        </div>
      <% end %>
    
      <p class="text-center mt10"><%= link_to "View all categories", categories_path %></p>
    </div>
  </div>
</section>
<section class="page-section">
  <div class="container">
    <h2 class="text-center">Latest Stores</h2>
    <div class="row pt6">
      <% @latest_stores.each do |s|%>
      <div class="col-sm-12 col-md-6">
        <div class="card">
         <h3><%= link_to s.name, s %></h3>
         <p>By <%= link_to s.user.username, s.user %></p> 
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

<section class="page-section">
  <h2 class="text-center">
    Latest products
  </h2>
  <div class="row pt6">
    <% @latest_products.each do |p| %>
      <div class="col-md-2 col-sm-2 col-xs-6 ">
        <div class="thumbnail">
          <%= image_tag(p.images[0]) %>
          <div class="caption">
            <h3><%= link_to p.name, p %></h3>
            <p class="amount"><%= number_to_currency(p.price, unit: "GHS") %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>
<section class="bottom-cta">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2>Claeus is the home of emerging brands. You can start <%= link_to "start selling", sell_path , class: 'base-link'%> online in 3 easy steps.</h2>
      </div>
    </div>
  </div>
</section>

app/views/pages/sell.html.erb
<div class="bg-white">
    <div class="container">
        <div class="text-center-xs mt5-xs mb7 mb3-xs">
            <div class="row ">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="ph6 pt6 pt0-sm pt0-xs">
                <h1 class="ma0">
                Shoppers can't wait to see your products
                </h1>
                <p class="lead mt4 mb5">Whether you sell online already or you've had ideas about selling online, Claeus give you the right tools just to get you started.</p>
                <%= link_to "Get started", new_store_path, class: "btn btn-danger btn-lg button" %>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>


<div class="bg-gray-super-light curve-container">
  <div class="curve"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-12">
        <div class="bg-white shadow-box pa6 home-shadow-box clearfix">

          <!-- <%= image_tag("shop.svg", width:"70px") %> -->
            <div class="text pl5">
            <h3 class="mt0 mb3 text-w-700">Create your Store</h3>
            <p class="ma0">Create a store easily.</p>
          </div>
        </div>
      </div>
    <div class="col-md-4 col-sm-12">
      <div class="bg-white shadow-box pa6 home-shadow-box clearfix">
        <!-- <%= image_tag("price-tag.svg", width: "70px") %> -->
        <div class="text pl5">
          <h3 class="mt0 mb3 text-w-700">Add your products</h3>
          <p class="ma0">Theres no limit to what you can sell.</p>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-12">
      <div class="bg-white shadow-box pa6 home-shadow-box clearfix">
        <!-- <%= image_tag("price-tag.svg", width: "70px") %> -->
        <div class="text pl5">
          <h3 class="mt0 mb3 text-w-700">Share with your followers</h3>
          <p class="ma0">Drive traffic to your awesome store by sharing ir with your followers.</p>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>


<div class=" bg-white home-feature-overview">
    <div class="container">
        <div class="row section mb7">
          <h3 class="text-center text-muted page-header">Features</h3>
            <div class="col-md-6 col-sm-12">
                <div class="media pb5">
                    <div class="media-left media-top">
                        <div class="icon"><%= image_tag("monitor.svg", class: "media-object img-responsive") %></div>
                    </div>
                    <div class="media-body media-top">
                        <h3 class="h-bold media-heading">Beautiful storefront</h3>
                        <p>Get started easily with a beautiful and mordern storefront.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="media pb5">
                    <div class="media-left media-top">
                        <div class="icon"><%= image_tag("note.svg", class: "media-object img-responsive") %></div>
                    </div>
                    <div class="media-body media-top">
                        <h3 class="h-bold media-heading">Email Marketing</h3>
                        <p>Capture email addresses and and let your contacts know your products and offers</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="media">
                    <div class="media-left media-top">
                        <div class="icon"><%= image_tag("internet.svg", class: "media-object img-responsive") %></div>
                    </div>
                    <div class="media-body media-top">
                        <h3 class="h-bold media-heading">Easy store management</h3>
                        <p>Manage everything from one Admin Panel</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="media pb5">
                    <div class="media-left media-top">
                        <div class="icon"><%= image_tag("responsive.svg", class: "media-object img-responsive") %></div>
                    </div>
                    <div class="media-body media-top">
                        <h3 class="h-bold media-heading">Responsive Design</h3>
                        <p>Your store works fine on all devices from Desktops to Laptops and smartphones.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="media pb5">
                    <div class="media-left media-top">
                        <div class="icon"><%= image_tag("commerce.svg", class: "media-object img-responsive") %></div>
                    </div>
                    <div class="media-body media-top">
                        <h3 class="h-bold media-heading">Online payment and invoicing</h3>
                        <p>Your store works fine on all devices from Desktops to Laptops and smartphones.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="media pb5">
                    <div class="media-left media-top">
                        <div class="icon"><%= image_tag("customer-service.svg", class: "media-object img-responsive") %></div>
                    </div>
                    <div class="media-body media-top">
                        <h3 class="h-bold media-heading">Help when you need it</h3>
                        <p>Your store works fine on all devices from Desktops to Laptops and smartphones.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>