config/routes.rb
Rails.application.routes.draw do

  resource :search, only: [:show]
  resources :stores, :except => [:index] do
    post 'follow', :to => 'followings#create'
    delete 'unfollow', :to => 'followings#destroy'
    collection do
      get 'dashboard'
    end
  end

  resources :products do
    resources :reviews, except: [:index, :show]

    collection do
      get 'search'
    end
  end

  get 'index', :to => 'pages#index'

  get 'sell', :to => 'pages#sell'

  get 'about', :to => 'pages#about'

  get 'contact', :to => 'pages#contact'

  get 'blog', :to => 'pages#blog'

  get 'support', :to => 'pages#support'

  get 'terms', :to => 'pages#terms'

  get 'privacy', :to => 'pages#privacy'

  get 'advertise', :to => 'pages#advertise'

  resources :categories, :only => [:index, :show]
  resources :subcategories, :only => [:index, :show]


  # get 'stores/dashboard'
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}

  # devise_scope :user do
  #   get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  resources :users, :only => [:show]
  root "pages#index"
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :images, ImageUploader

  belongs_to :store
  has_many :reviews
  belongs_to :category
  belongs_to :subcategory
  validates :name, :price, :description, :category, :images, :stock, presence: true
  validates :slug, uniqueness: true, presence: true

  before_validation :generate_slug

  def to_param
    "#{id}-#{name}".parameterize
  end

  def generate_slug
    self.slug ||= name.parameterize
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def new
    @product = Product.new
  end

  def show
    @r = Review.new
    @review = Review.where(product_id: @product)

    if @review.blank?
      @avg_rating = 0
    else
      @avg_rating = @product.reviews.average(:rating).round(2)
    end
  end

  def search
    @products = Product.search(params)
  end

  def create
    @product = Product.new(product_params)
    @product.store_id = current_user.store.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/1
  # DELETE /product/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to @product.store, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :store_id, :stock, :category_id, :subcategory_id, {images: []})
    end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product , html: { multipart: true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control input-lg" %>
      <small>Add a name to your item. eg. iPhone 7 32GB</small>
    </div>

    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.order(:name), :id, :name, {include_blank: true}, {class: "form-control input-lg"} %>
      <small>Select a Category</small>
    </div>

    <div class="form-group">
      <%= f.label :subcategory_id %>
      <%= f.grouped_collection_select :subcategory_id, Category.order(:name), :subcategories, :name, :id, :name, {include_blank: true}, {class: "form-control input-lg"} %>
      <small>Select a Subcategory</small>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control input-lg" %>
      <small>Provide a very good description for your item. Remember good description attracts!</small>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control input-lg" %>
      <small>Add your item price per unit.</small>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :stock %>
      <%= f.text_field :stock, class: "form-control input-lg" %>
      <small>How many of this product do you have to offer?</small>
    </div>

    <div class="pdt-assets">
        <%= f.label :images %>
        <%= f.file_field :images, multiple: true %>
        <small>You can select up to 5 images, the first will be used as the feature image.</small>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-danger btn-block btn-lg" %>
  </div>
  <hr>
<% end %>

app/views/products/edit.html.erb
<div class="section pt6">
  <div class="container">
    <div class="row  mb7">
      <div class="col-sm-8 col-sm-offset-2">
      	<div class="panel panel-danger">
      		<div class="panel-heading">
      		<p class="lead">Edit <%= @product.name %></p></div>
      		<div class="panel-body">
      		<br>
      			<%= render "form" %>
      		</div>
      	</div>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container pt6">
	<div class="row  mb7">
  	<div class="col-sm-8 col-sm-offset-2">
  		<div class="panel panel-danger">
  			<div class="panel-heading">New Product</div>
  			<div class="panel-body">
  			<br>
	        <%= render 'form' %>
  			</div>
  		</div>
    </div>
  </div>
</div>

app/views/products/search.html.erb
<div class="section">
	<div class="container-fluid">
		<div class="col-md-12">
			<div class="panel panel-danger">
          <div class="panel-heading">Search results</div>
        	<div class="panel-body">
          	<div class="search">
          		<div class="row">
							<% if @products.blank? %>
							  <h3 class="textcenter lead">
							  	We could not find a product that matches your criteria!!
							  </h3>
							<% else %>
							  <% @products.each do |product| %>
									<div class="col-md-3 col-sm-6 col-lg-2">
										<div class="thumbnail">
											<%= image_tag product.images[0].asset, class: "img-responsive" %>
											<div class="caption">
											<h3><%= link_to product.name, product %></h3>
											<span class="amount">GHS <%= product.price %></span>
											</div>
										</div>
									</div>
								<% end %>
							<% end %>
							
							</div>
          	</div>	
        	</div>
    	</div>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<% content_for :title, @product.name %>
<% content_for :description, @product.description %>
<div class=" section mt10 mb7">
    <div class="container ">
      <div class="panel panel-danger">
        <div class="panel-body">
          <div class="row pt6">
            <div class="col-sm-7">
              <%= image_tag @product.images[0].medium, class: "img-responsive" %>
            </div>
            <div class="col-sm-5">
               <span class="label label-danger">
              <%=  @product.category.name %>
            </span>
            <p class="lead">By: <%= link_to @product.store.name.capitalize, store_path(@product.store), class: "btn btn-link" %></p>
            <h3><%= @product.name.capitalize %></h3>
            <span class="star-rating" data-score=<%= @avg_rating %>></span> |  <span><%= @product.reviews.count %> Customer reviews</span>
            <h4 class="amount"> <%= number_to_currency(@product.price) %></h4>
            <label>Description:</label>
            <p><%= @product.description%></p>
            <hr>
            <!-- <button type="button" name="button" class="btn btn-danger">Contact Seller</button>
            <button type="button" name="button" class="btn btn-danger">Add to cart</button> -->


            <% if (user_signed_in?) && (current_user == @user) %>
              <%= link_to "Edit", edit_product_path(@product) %>
              <%= link_to 'Back', products_path %>
              <%= link_to "Delete", @product, method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
            </div>
          </div>

          <hr>
          <br>

          <div class="container">

            <ul class="nav nav-pills">
              <li role="presentation" class="active"><a href="#gallery" data-toggle="tab">Gallery</a></li>
              <li role="presentation"><a href="#reviews" data-toggle="tab">Reviews</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane fade in active" id="gallery" >
                  <div class="row pt6">
                    <% for image in @product.images %>
                    <div class="col-sm-6 col-sm-offset-3 clearfix">
                      <div class="thumbnail">
                        <div class="img-responsive">
                          <%= image_tag image.medium %>
                        </div>
                      </div>
                    </div>
                    <% end %>
                  </div>
                </div>

                <div class="tab-pane fade in pt6" id="reviews" >
                  <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                      <p class="lead "><strong>Reviews</strong></p>
                      <div class="pt6">
                        <span>Already purchaed this product?Write a review </span>
                          <%= render 'reviews/form' %>
                      </div>
                      <hr>
                       <% if @review.blank? %>
                         <p>No reviews yet</p>
                       <% else %>
                         <% @review.each do |r| %>
                           <div class="star-rating" data-score=<%= r.rating %>></div>
                           <p><%= r.comment %></p>
                           <span>By: <%= r.user.username %></span>
                         <% end %>
                       <% end %>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>


    </div>
</div>