config/routes.rb
Rails.application.routes.draw do

  resource :search, only: [:show]
  resources :stores, :except => [:index] do
    post 'follow', :to => 'followings#create'
    delete 'unfollow', :to => 'followings#destroy'
    collection do
      get 'dashboard'
    end
  end

  resources :products do
    resources :reviews, except: [:index, :show]

    collection do
      get 'search'
    end
  end

  get 'index', :to => 'pages#index'

  get 'sell', :to => 'pages#sell'

  get 'about', :to => 'pages#about'

  get 'contact', :to => 'pages#contact'

  get 'blog', :to => 'pages#blog'

  get 'support', :to => 'pages#support'

  get 'terms', :to => 'pages#terms'

  get 'privacy', :to => 'pages#privacy'

  get 'advertise', :to => 'pages#advertise'

  resources :categories, :only => [:index, :show]
  resources :subcategories, :only => [:index, :show]


  # get 'stores/dashboard'
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}

  # devise_scope :user do
  #   get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  resources :users, :only => [:show]
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products, through: :subcategories
  has_many :subcategories
  has_many :stores

end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :store
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :reciepient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true

  scope :unread, ->{ where(read_at: nil) }
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :images, ImageUploader

  belongs_to :store
  has_many :reviews
  belongs_to :category
  belongs_to :subcategory
  validates :name, :price, :description, :category, :images, :stock, presence: true
  validates :slug, uniqueness: true, presence: true

  before_validation :generate_slug

  def to_param
    "#{id}-#{name}".parameterize
  end

  def generate_slug
    self.slug ||= name.parameterize
  end
end

app/models/review.rb
class Review < ApplicationRecord

    belongs_to :product
    belongs_to :user

    validates :comment, :rating, presence: true
    
end

app/models/search.rb
class Search
	attr_reader :term

	def to_partial_path
		'searches/show'
	end

	def initialize(options = {})
		@term = options.fetch(:term, "")
	end

	def found_products
		products
	end

	def found_stores
		stores
	end

	private

	def stores
		@store = Store.where("name iLike ? or description iLike ?", search_term, search_term)
	end

	def products
    @products = Product.where("name iLIKE ? or description iLIKE ?", search_term, search_term)
	end

	def search_term
		"%#{term}%"
	end
	
end

app/models/store.rb
class Store < ApplicationRecord
  is_impressionable
  RESTRICTED_NAMES = %w[www]

  mount_uploader :logo, ImageUploader

  belongs_to :user
  belongs_to :category
  
  
  has_many :followings
  has_many :followers, through: :followings


  has_many :products, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :name, presence: true,
                  uniqueness: { case_sensitive: false},
                  format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters'},
                  exclusion: { in: RESTRICTED_NAMES, message: 'restricted'}

  validates :description, :category, presence: true
  validates :slug, uniqueness: true, presence: true

  before_validation :generate_slug

  
  # Get all stores tagged with name

  def self.tagged_with(name)
    Tag.find_by!(name: name).stores
  end

  # tags and taggings setting tags
    def all_tags=(names)
      self.tags = names.split(',').map do |name|
        Tag.where(name: name).first_or_create!
      end
    end

  # Getting tags
    def all_tags
      tags.map(&:name).join(", ")
    end

  # COnverts id and name to string for pretty urls
    def to_param
      "#{id}-#{name}".parameterize
    end

  # Generates slug for future use
    def generate_slug
      self.slug ||= name.parameterize
    end


end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  
  belongs_to :category
  has_many :products

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :stores, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord

  belongs_to :store
  belongs_to :tag
  
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable , :confirmable, :omniauthable, :omniauth_providers => [:facebook]

  mount_uploader :avatar, ImageUploader

  has_one :store, dependent: :destroy
  has_many :reviews
  has_many :notifications, foreign_key: :reciepient_id
  
  # accepts_nested_attributes_for :store

  def following? store, user
    store.follower_ids.include? user.id
  end

  def follow (store, user)
    store.followers << user
  end

  def unfollow (store, user)
    store.followers.delete(user.id)
  end

  

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|

      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name # assuming the user model has a name
      user.remote_avatar_url = auth.info.image

      # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      #  user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/form_helper.rb
module FormHelper

  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: "help-block")
  end


  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors} " do
      concat form.label(field, class: "control-label") if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end

end

app/helpers/layout_helper.rb
module LayoutHelper

  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash-#{name}")
      end
    end
  end

  def show_layout_flash
    @layout_flash.nil? ? true : @layout_flash
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/steppy_helper.rb
module SteppyHelper
end

app/helpers/store_helper.rb
module StoreHelper
	def follow_button store

		if  current_user && current_user != store.user 
			if current_user.following?(store, current_user)
				button_to 'Unfollow', store_unfollow_path(store), method: :delete, class: "btn btn-danger button"
			else
				button_to 'Follow', store_follow_path(store), class: "btn btn-danger button"
			end
		end
		
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer-primary clearfix">
    <div class="container">
        <div class="row">
            <div class="col-sm-3 col-xs-12 pbm">
            <p class="lead amount"><strong>Claeus, Inc.</strong></p>
            </div>
            <div class="col-sm-2 col-sm-offset-2 col-xs-4 col-xs-offset-0">
                <h4 class="h-bold">Company</h4>
                <ul class="list-unstyled">
                    <li><%= link_to "About Us", about_path %></li>
                    <!-- <li><%= link_to "Blog", blog_path %></li> -->
                    <li><%= link_to "Contact Us", contact_path %></li>
                </ul>
                <div class="fb-like" data-href="http://www.claeus.com/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
            </div>
            <div class="col-sm-2 col-sm-offset-1 col-xs-4 col-xs-offset-0">
                <h4 class="h-bold">Business</h4>
                <ul class="list-unstyled">
                    <li><%= link_to "Sell on Claeus", sell_path %></li>
                    <!-- <li><%= link_to "Advertise", advertise_path %></li> -->
                    <li><%= link_to "FAQs", support_path %></li>
                </ul>
            </div>
            <!-- <div class="col-sm-2 col-xs-4 col-xs-offset-0">
                <h4 class="h-bold">Help</h4>
                <ul class="list-unstyled">
                    <li><%= link_to "Support", support_path %></li>
                    <li><%= link_to "Privacy", privacy_path %></li>
                    <li><%= link_to "Terms", terms_path %></li>
                </ul>
            </div> -->
        </div>
        <div class="row pt6">
            <div class="col-sm-12">
              <div class="text-center">
                <p class=" footer-copyright">
                    ©
                    2017
                    claeus. All Rights Reserved.
                </p>
              </div>

            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-primary navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar-collapse" aria-expanded="false">
        <i class="fa fa-bars" aria-hidden="true"></i>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag("claeus-02.svg", alt: "claeus-logo-black") %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="header-navbar-collapse" class="collapse navbar-collapse">
        <div class="navbar-form navbar-left">
          <div class="form-group"  id="navSearch">
            <%= form_for(:search, url: search_path, method: :get) do |f| %>
              <div class="input-group">
                <%= f.text_field :term %>
                
              </div>
            <% end %>
          </div>
        </div>
      <div class=" navbar-right">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>

            <% if current_user.store %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Store<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Admin panel", dashboard_stores_url %></li>
                <li><%= link_to "Stats", dashboard_stores_url %></li>
                <li><%= link_to "Add new product", new_product_path %></li>
                <li><%= link_to "Storefront", store_path(current_user.store) %></li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Sell on claeus", sell_path %></li>
            <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Visit Profile", user_path(current_user) %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Sell on claeus", sell_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <%= link_to "Join", new_user_registration_path, class: "btn btn-danger btn-sm navbar-btn" %>
          <% end %>

          </ul>

      </div>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <% if Rails.env == "production" %>
      <script>
        (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-6569617553535399",
          enable_page_level_ads: true
        });
      </script>
    <% end %>


    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Claeus - Online marketplace for emerging brands."%></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

  <% if current_page?(root_path) %>
    <body class="bg-white">
  <% else %>
    <body class="bg-grey">
  <% end %>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9&appId=1960576137506127";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


    
    <%= render 'layouts/header' %>

        <% if notice.present? %>
          <div id="notice_wrapper">
            <p class="notice"><%= notice %></p>
          </div>
        <% elsif alert.present? %>
          <div id="alert_wrapper">
            <p class="alert"><%= alert %></p>
          </div>
        <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>


    <script>
      $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function() {
              return $(this).attr('data-score');
      }
    });
  </script>

  <% if Rails.env == "production" %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-99584135-1', 'auto');
      ga('send', 'pageview');

    </script>
  <% end %>
  </body>
</html>